# Generated by Django 5.2.6 on 2025-10-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rate',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
